### ISSUE TITLE
Object properties with underscore are ignored

### ISSUE THREAD

**Issue by jzernovic** [QualityUnit/LiveAgent-api-scala-akka#1]
**Example:**
I'm calling APIv3 call to get connected email account by email address. The request is sent, successfully arrives into APIv3 enpoint, gets processed and returns something like this:
```
Array
(
    [mailaccount_id] => zMozg6xU
    [fetch_type] => I
    [email] => test@email.address
    [department_id] => default
    [status] => A
    [provider] => gmailOAuth
    [last_mail_date] =>
    [last_fetch_date] =>
)
```
but when it is deserialized to generated scala case class it looks like this:
```
MailAccount(None,None,Some(test@email.address),None,Some(A),Some(gma
ilOAuth),None,None)
```

As can be seen filled are only properties, that does not have underscore in their names as the case class properties are converted to camelCase notation from liveagent.yaml definition:
```
MailAccount:
    description: Mail account
    type: object
    properties:
      mailaccount_id:
        type: string
      fetch_type:
        type: string
        description: |
          I - Imap, 3 - POP3, P - piping, B - built-in, F - forwarding
      email:
        type: string
      department_id:
        type: string
      status:
        type: string
        description: |
          A - active, I - inactive, P - pending, S - skipping
      provider:
        type: string
      last_mail_date:
        type: string
      last_fetch_date:
        type: string
```

So the `mailaccount_id` property name from yaml defininition is converted to `mailaccountId` in generated scala case class property.
